"""empty message

Revision ID: 3990bf9187e5
Revises: 6f5351e57ad0
Create Date: 2026-03-05 15:01:43.113433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3990bf9187e5'
down_revision = '6f5351e57ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_uuid'))
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
